data_file: ./data/test.mat
gdth_file: ./data/3c353_gdth.fits
result_path: ./results
nufft_pkg: finufft
super_resolution: 1.5
target_dynamic_range_heuristic: 1.e+4
data_weighting: True
load_weight: False
weight_type: briggs
weight_gridsize: 2
weight_robustness: 0
meas_op_on_gpu: True
nufft_oversampling_factor: 2.0
nufft_kernel_dim: 7
nufft_mode: table